name: Build and push Seafile image

on: [push]

jobs:
  build_and_push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: "${{ secrets.DOCKER_HUB_USERNAME }}/seafile-armhf"
      DOCKER_USERNAME: "${{ secrets.DOCKER_HUB_USERNAME }}"
      DOCKER_PASSWORD: "${{ secrets.DOCKER_HUB_PASSWORD }}"
      DOCKER_TARGET_PLATFORM: linux/arm/v7
    steps:
      - name: Check out our repo
        uses: actions/checkout@v2
      - name: Checkout SeaFile repo
        uses: actions/checkout@v2
        with:
          repository: haiwen/seafile-docker
          path: seafile-docker
      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: Docker Login
        if: success()
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      - name: Run Buildx (push image)
        if: success()
        run: |
          docker buildx build \
          --platform ${DOCKER_TARGET_PLATFORM} \
          --tag ${DOCKER_IMAGE}:latest \
          --file ./Dockerfile \
          --output type=image,push=true .
